name: bottom_sheet_bar_example
description: An example app using the `bottom_sheet_bar` package

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.1.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bottom_sheet_bar:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
